-- MySQL Script generated by MySQL Workbench
-- Mon Nov  2 14:18:43 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ontologydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ontologydb` ;

-- -----------------------------------------------------
-- Schema ontologydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ontologydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `ontologydb` ;

-- -----------------------------------------------------
-- Table `ontologydb`.`ONTOLOGY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ontologydb`.`ONTOLOGY` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ontologydb`.`ONTOLOGY` (
  `ontology_id` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `version_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ontology_id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ontologydb`.`DOMAIN_ONTOLOGY_MAPPING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ontologydb`.`DOMAIN_ONTOLOGY_MAPPING` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ontologydb`.`DOMAIN_ONTOLOGY_MAPPING` (
  `domain_ontology_map_id` INT NOT NULL,
  `domain_id` INT NOT NULL,
  `ontology_id` INT NOT NULL,
  PRIMARY KEY (`domain_ontology_map_id`, `domain_id`),
  CONSTRAINT `ontology_id`
    FOREIGN KEY (`ontology_id`)
    REFERENCES `ontologydb`.`ONTOLOGY` (`ontology_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


