hello.value: Maven
secret: secret
app.docs: http://localhost:8090

spring:
  profiles: default

spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: 'jdbc:mysql://${db.host:localhost}:${db.port:3306}/ontologydb'
  username: apps
  password: H0meRun
  initialSize: 5
  minIdle: 5
  maxActive: 30
  maxIdle: 30
  maxWait: 5000
  defaultAutoCommit: false
  validationQuery: SELECT 1
  testOnBorrow: true
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 10000
  minEvictableIdleTimeMillis: 30000
  jmxEnabled: true
  removeAbandonedTimeout: 120
  removeAbandoned: true

db:
  host: stagedb03.nb
  port: 3306
  hibernate:
    debug:
      sql:
        enabled: false
        formatted: false
        use_comments: false
    cache:
      query: true
      second_level: true
# Server
server:
  port: ${port:8090}

# Management
management:
  port: ${mport:8081}
  context-path: /manage


ssl:
  keystore:
      fileLocation: misc/phissl.jks
      keystorePassword: changeit
      keyPassword: changeit
      alias: phissl

https:
  port: 8443

encryption:
  keystore:
    fileLocation: misc/keystore.jks
    keystorePassword: changeit
    alias: ephikey
    keyPassword: changeit

# Sets the maximum file size limit for multipart upload
# Note: The maximum file size is also needed to be configured properly in MySQL configuration file (via `max_allowed_packet`),
#       because currently we store the binary in MySQL.
#       And there is a hard limit on MySQL's `max_allowed_packet`, which is 1GB (version 5.5~5.7).
#       The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size.
#       So MySQL `innodb_log_file_size` needs to be increased accordingly as well
# Reference: https://dev.mysql.com/doc/refman/5.7/en/packet-too-large.html
#            https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_max_allowed_packet
#            https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_log_file_size
multipart:
  maxFileSize: 100MB
  maxRequestSize: 150MB

#platform integration params
remote:
  service:
    userauth:
      baseurl: "https://platform.use1.informatics.testing-domain.illumina.com/platform-services-manager/"
      clientId: "ephi-logs"
      clientSecret: "!ephilogs@#%"
      accessTokenHeader: "psToken"
      tokenUrlPath: "/auth/validateToken"
